// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerVital.Data;

#nullable disable

namespace PowerVital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Padecimiento", b =>
                {
                    b.Property<int>("IdPadecimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPadecimiento"));

                    b.Property<string>("AreaMuscularAfectada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPadecimiento");

                    b.ToTable("Padecimientos");
                });

            modelBuilder.Entity("PowerVital.Models.Ejercicio", b =>
                {
                    b.Property<int>("IdEjercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEjercicio"));

                    b.Property<string>("AreaMuscular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaMuscularAfectada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuiaEjercicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.HasKey("IdEjercicio");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("PowerVital.Models.EjercicioRutina", b =>
                {
                    b.Property<int>("IdRutina")
                        .HasColumnType("int");

                    b.Property<int>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EjercicioIdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("RutinaIdRutina")
                        .HasColumnType("int");

                    b.HasKey("IdRutina", "IdEjercicio");

                    b.HasIndex("EjercicioIdEjercicio");

                    b.HasIndex("RutinaIdRutina");

                    b.ToTable("EjercicioRutina");
                });

            modelBuilder.Entity("PowerVital.Models.HistorialSalud", b =>
                {
                    b.Property<int>("IdHistorialSalud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialSalud"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IndiceMasaCorporal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdHistorialSalud");

                    b.HasIndex("ClienteId");

                    b.ToTable("HistorialesSalud");
                });

            modelBuilder.Entity("PowerVital.Models.PadecimientoCliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPadecimiento")
                        .HasColumnType("int");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente", "IdPadecimiento");

                    b.HasIndex("IdPadecimiento");

                    b.ToTable("PadecimientoCliente");
                });

            modelBuilder.Entity("PowerVital.Models.PadecimientoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HistorialSaludId")
                        .HasColumnType("int");

                    b.Property<int?>("PadecimientoId")
                        .HasColumnType("int");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HistorialSaludId");

                    b.HasIndex("PadecimientoId");

                    b.ToTable("PadecimientosHistorial");
                });

            modelBuilder.Entity("PowerVital.Models.Rutina", b =>
                {
                    b.Property<int>("IdRutina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutina"));

                    b.Property<int>("ClienteIdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("IdRutina");

                    b.HasIndex("ClienteIdUsuario");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("PowerVital.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Rol").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PowerVital.Models.Administrador", b =>
                {
                    b.HasBaseType("PowerVital.Models.Usuario");

                    b.Property<string>("titulacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("PowerVital.Models.Cliente", b =>
                {
                    b.HasBaseType("PowerVital.Models.Usuario");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoPago")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("EntrenadorId");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("PowerVital.Models.Entrenador", b =>
                {
                    b.HasBaseType("PowerVital.Models.Usuario");

                    b.Property<string>("FormacionAcademica")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Entrenador");
                });

            modelBuilder.Entity("PowerVital.Models.EjercicioRutina", b =>
                {
                    b.HasOne("PowerVital.Models.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioIdEjercicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerVital.Models.Rutina", "Rutina")
                        .WithMany("EjerciciosRutina")
                        .HasForeignKey("RutinaIdRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("PowerVital.Models.HistorialSalud", b =>
                {
                    b.HasOne("PowerVital.Models.Cliente", "Cliente")
                        .WithMany("HistorialesSalud")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PowerVital.Models.PadecimientoCliente", b =>
                {
                    b.HasOne("PowerVital.Models.Cliente", "Cliente")
                        .WithMany("PadecimientosClientes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padecimiento", "Padecimiento")
                        .WithMany("PadecimientosClientes")
                        .HasForeignKey("IdPadecimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Padecimiento");
                });

            modelBuilder.Entity("PowerVital.Models.PadecimientoHistorial", b =>
                {
                    b.HasOne("PowerVital.Models.HistorialSalud", "HistorialSalud")
                        .WithMany("Padecimientos")
                        .HasForeignKey("HistorialSaludId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padecimiento", "Padecimiento")
                        .WithMany("PadecimientosHistorial")
                        .HasForeignKey("PadecimientoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("HistorialSalud");

                    b.Navigation("Padecimiento");
                });

            modelBuilder.Entity("PowerVital.Models.Rutina", b =>
                {
                    b.HasOne("PowerVital.Models.Cliente", "Cliente")
                        .WithMany("Rutinas")
                        .HasForeignKey("ClienteIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PowerVital.Models.Cliente", b =>
                {
                    b.HasOne("PowerVital.Models.Entrenador", "Entrenador")
                        .WithMany("Clientes")
                        .HasForeignKey("EntrenadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("Padecimiento", b =>
                {
                    b.Navigation("PadecimientosClientes");

                    b.Navigation("PadecimientosHistorial");
                });

            modelBuilder.Entity("PowerVital.Models.HistorialSalud", b =>
                {
                    b.Navigation("Padecimientos");
                });

            modelBuilder.Entity("PowerVital.Models.Rutina", b =>
                {
                    b.Navigation("EjerciciosRutina");
                });

            modelBuilder.Entity("PowerVital.Models.Cliente", b =>
                {
                    b.Navigation("HistorialesSalud");

                    b.Navigation("PadecimientosClientes");

                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("PowerVital.Models.Entrenador", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
